### ISSUE TITLE
全局变量API 按照例子后，仍然提示找不到模块

### ISSUE THREAD

**Issue by LbhFront-end** [alibaba/pont#118]
## What happens(发生了什么)?

全局变量API 按照例子后，仍然提示找不到模块
**tsconfig.json**
```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "esnext",
    "lib": [
      "esnext",
      "dom"
    ],
    "sourceMap": true,
    "baseUrl": ".",
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "strict": true,
    "paths": {
      "@/*": [
        "./src/*"
      ]
    }
  },
  "include": ["./src/services/api.d.ts", "./src/**/*"],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "src/services",
    "tslint:latest",
    "tslint-config-prettier"
  ]
}
```
![image](https://user-images.githubusercontent.com/30042334/68171917-9cb5d500-ffb0-11e9-8c26-6a11b263ecb4.png)
![image](https://user-images.githubusercontent.com/30042334/68171924-a2131f80-ffb0-11e9-9e2d-99385f06abaf.png)

另外如果导入 `import @/services/api` 可以解决报红的问题，但是会提醒需要安装该模块

![image](https://user-images.githubusercontent.com/30042334/68172002-eacad880-ffb0-11e9-9120-d4b947c3c521.png)

**后续**
1.修改成 `import '@/services/api.d.ts'` 解决了问题，但是这就意味着需要每个文件都要引入，不知道为什么 `tsconfig.json`的 include 文件不会生效
2. 尝试在全局布局增加声明
情况1：
```ts
import '@/services/api.d.ts'
```
编译错误
```shell
 error  in ./src/services/api.d.ts

Module build failed (from ./node_modules/_ts-loader@6.0.3@ts-loader/index.js):
Error: Debug Failure. Output generation failed
    at Object.transpileModule (F:\GitLab\M2B-TS\node_modules\_typescript@3.5.2@typescript\lib\typescript.js:109382:29)
    at getTranspilationEmit (F:\GitLab\M2B-TS\node_modules\_ts-loader@6.0.3@ts-loader\dist\index.js:283:74)
    at successLoader (F:\GitLab\M2B-TS\node_modules\_ts-loader@6.0.3@ts-loader\dist\index.js:66:15)
    at Object.loader (F:\GitLab\M2B-TS\node_modules\_ts-loader@6.0.3@ts-loader\dist\index.js:22:12)

 @ ./src/layouts/SecurityLayout.tsx 30:0-30
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/_af-webpack@1.11.7@af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```
情况2：
```ts
/// <reference path="@/services/api.d.ts"/>
```
编译没有报错，但是仍然找不到全局模块

## 希望可以解决的问题
1. 这个文件要怎么全局引入，才不会报警告或者编译错误

**Comment by dreamstarch** [comment]
five lbh

**Comment by LbhFront-end** [comment]
在布局里面声明了，解决了问题。
![image](https://user-images.githubusercontent.com/30042334/68185413-6f7f1c00-ffdc-11e9-8fbe-1e543266d707.png)

**Comment by 540240126** [comment]
虽然你include了api.d.ts文件，但是你下面的exclude又排除掉整个文件夹了

**Comment by LbhFront-end** [comment]
> 虽然你include了api.d.ts文件，但是你下面的exclude又排除掉整个文件夹了

好的 谢谢 虽然后面没有用这个工具了，全部手写类型。不过挺麻烦的

**Comment by 540240126** [comment]
为啥不用了，手写那不累死

**Comment by LbhFront-end** [comment]
> 为啥不用了，手写那不累死

后端总有很多理由，麻烦是麻烦，百来个接口吧，但是没有什么办法

**Comment by 540240126** [comment]
那倒是，后端要是不配合是不好搞，我以为是你觉得这工具不好用，既然不是那我就放心了

**Comment by LbhFront-end** [comment]
> 那倒是，后端要是不配合是不好搞，我以为是你觉得这工具不好用，既然不是那我就放心了

说是swagger本身的缺陷，后端没有办法配合得很好，再问具体的就不跟我说了
