### ISSUE TITLE
读取远程接口数据失败！TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by CaicoLeung** [alibaba/pont#127]
## What happens(发生了什么)?
Error: 读取远程接口数据失败！TypeError: Cannot read property 'push' of undefined
A clear and concise description of what the bug is(对错误的清晰而简明的描述).
执行"pont check"指令, 提示错误
## Mini Showcase Repository(迷你展示库)

> Provide a mini GitHub repository which can reproduce the issue(提供一个可以重现问题的小型 Github 存储库).
https://github.com/CaicoLeung/Pont-Demo.git

## How To Reproduce(如何重现)
官方demo的swagger.json正常, 自己生成的swagger.json的解析报错, 必现
**Steps to reproduce the behavior(重现行为的步骤):** 1. 2.
pont check
**Expected behavior(预期行为)** 1. 2.

## Context(上下文)
获取远程数据中...
自动翻译中文基类中...
自动翻译中文基类完成！
远程数据获取成功！
Error: 读取远程接口数据失败！TypeError: Cannot read property 'push' of undefined
    at SwaggerV2Reader.<anonymous> (/home/caico/.nvm/versions/node/v10.16.3/lib/node_modules/pont-engine/lib/scripts/base.js:88:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/caico/.nvm/versions/node/v10.16.3/lib/node_modules/pont-engine/lib/scripts/base.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 读取远程接口数据失败！TypeError: Cannot read property 'push' of undefined

- **pont Version**: 0.3.4
- **Node Version**:  10.16.3
- **Platform(操作系统平台)**: linux windows

**Comment by linningmii** [comment]
fix版本已发布
