### ISSUE TITLE
已经全局安装并使用pont start生成配置文件，但使用pont all 时报错Cannot find module 'pont-engine'

### ISSUE THREAD

**Issue by birdycn** [alibaba/pont#212]
```
 C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\bin\init.js
    at Object.getTemplate (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\utils.js:326:19)
    at Manager.setFilesManager (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:332:82)
    at Manager.getGeneratedFiles (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:303:14)
    at Manager.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:326:32)
    at Generator.next (<anonymous>)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:4:12)
    at Manager.regenerateFiles (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:325:16)
    at Manager.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\manage.js:147:28)
Error: Error: Cannot find module 'pont-engine'
Require stack:
- D:\Code\xxx\pontTemplate105.js
- C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\utils.js
- C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\lib\cmd.js
- C:\Users\xxx\AppData\Roaming\npm\node_modules\pont-engine\bin\init.js```

**Comment by birdycn** [comment]
又遇到这个问题了。

**Comment by liuwei1025** [comment]
+1 不知道为啥会从当前目录引用 `pont-engine`

**Comment by liuwei1025** [comment]
> +1 不知道为啥会从当前目录引用 `pont-engine`

README中有写 需要自己安装`pont-engine`
```
// npm
npm i -g pont-engine

// 或yarn
yarn global add pont-engine
```

**Comment by ranwawa** [comment]
+1
