### ISSUE TITLE
compiler error in defname

### ISSUE THREAD

**Issue by youth95** [alibaba/pont#71]
获取远程数据中...
自动翻译中文基类中...
自动翻译中文基类完成！
远程数据获取成功！
Error: 读取远程接口数据失败！Error: compiler error in defname: create.AccountGroupRelationCreate
    at SwaggerV2Reader.<anonymous> (/Users/zhaozhaoqian/projects/gs_cloud_swagger_api/node_modules/pont-engine/lib/scripts/base.js:81:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/zhaozhaoqian/projects/gs_cloud_swagger_api/node_modules/pont-engine/lib/scripts/base.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: 读取远程接口数据失败！Error: compiler error in defname: create.AccountGroupRelationCreate

defname 中目前不支持一些特殊字符

**Comment by linningmii** [comment]
能提供一下api-docs吗？

**Comment by jasonHzq** [comment]
defName 包含 .，PR 已合并，已修复
